# Generated by Django 4.0.4 on 2022-06-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nombre',
            new_name='rol',
        ),
    ]
