# Generated by Django 4.0.4 on 2022-06-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_nombre_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='año_i',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='AÑO INGRESO'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default=None, max_length=250, verbose_name='DIRECCIÓN RESIDENCIA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='f_grado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FECHA DE GRADO'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_n',
            field=models.CharField(default=None, max_length=250, verbose_name='FECHA DE NACIMIENTO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='l_espedicion',
            field=models.CharField(default=None, max_length=250, verbose_name='LUGAR DE EXPEDICIÓN ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='l_nacimiento',
            field=models.CharField(default=None, max_length=250, verbose_name='LUGAR DE NACIMIENTO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='n_emergencia',
            field=models.CharField(default=None, max_length=250, verbose_name='EN CASO DE EMERGENCIA LLAMAR A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='ni',
            field=models.BigIntegerField(default=None, verbose_name='Numero de identificacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_emergencia',
            field=models.CharField(default=None, max_length=250, verbose_name='NÚMERO DE CONTACTO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='posgrado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='POSGRADOS'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pregrado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PREGRADO'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='programa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='semestre_a',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='SEMESTRE ACTUAL'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.BigIntegerField(default=None, verbose_name='TELÉFONO/ CELULAR'),
            preserve_default=False,
        ),
    ]
