# Generated by Django 4.0.4 on 2022-06-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_id_semillero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(default='estudiante', max_length=250, null=True),
        ),
    ]
