# Generated by Django 4.0.4 on 2022-06-13 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0005_alter_perfil_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id_semillero',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
