# Generated by Django 4.0.4 on 2022-06-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0003_remove_semillero_id_users'),
        ('usuarios', '0006_remove_perfil_id_semillero_alter_perfil_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='id_semillero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='semilleros.semillero'),
            preserve_default=False,
        ),
    ]
