# Generated by Django 4.0.4 on 2022-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfil_id_semillero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ni',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Numero de identificacion'),
        ),
    ]
