# Generated by Django 4.0.4 on 2022-06-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_perfil_id_alter_perfil_ni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id_semillero',
        ),
    ]
