# Generated by Django 4.0.4 on 2022-06-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_perfil_id_semillero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id_semillero',
        ),
    ]
