# Generated by Django 4.0.4 on 2022-06-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0008_remove_semillero_id_users'),
        ('usuarios', '0012_remove_perfil_id_semillero'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='id_semillero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='semilleros.semillero'),
        ),
    ]
