# Generated by Django 4.0.4 on 2022-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='NOMBRE DEL SEMILLERO')),
                ('facultad', models.CharField(max_length=250, verbose_name='FACULTAD')),
                ('programa_academico', models.CharField(max_length=250, verbose_name='PROGRMA ACADÉMICO')),
                ('g_investigacion', models.CharField(max_length=250, verbose_name='GRUPO DE INVESTIGACIÓN AL CUAL ESTÁ VINCULADO EL SEMILLERO')),
                ('l_investigacion_asociado', models.CharField(max_length=250, verbose_name='LÍNEA Y SUBLÍNEA DE INVESTIGACIÓN ASOCIADOS')),
                ('tematica', models.CharField(max_length=250, verbose_name='TÉMATICA DE ESTUDIO DEL SEMILLERO')),
                ('justificacion', models.TextField(verbose_name=' JUSTIFICACIÓN DEL SEMILLERO DE INVESTIGACIÓN')),
                ('status', models.BooleanField(default=False, verbose_name='Aprobacion')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
