# Generated by Django 4.0.4 on 2022-06-15 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semilleros', '0004_semillero_id_semillero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='id_semillero',
        ),
        migrations.AddField(
            model_name='semillero',
            name='id_users',
            field=models.ManyToManyField(related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
