# Generated by Django 4.0.4 on 2022-06-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0005_remove_semillero_id_semillero_semillero_id_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='id_users',
        ),
    ]
