# Generated by Django 4.0.4 on 2022-06-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semilleros', '0006_remove_semillero_id_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='id_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
